build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs"
  contactDetails:
    name: "Arbi Dwi Wijaya - QA Lead"
    email: "arbiqa@mail.com"
  onCallSupport:
    - (62) 8111222666
    - (62) 8222333555